### ISSUE TITLE
Histogram chart xmin and xmax

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#10]
Hi Karl,

As discussed, could you change the histogram widget in such a way that:
- if no xmin and xmax provided: automatically take xmin=min(values) and xmax=max(values)
- if specific xmin and xmax are provided: take these to determine the range of data values to include in the histogram. Do not add outliers to the bins.

Thank you

**Comment by karlduderstadt** [comment]
The commit above adds this feature. It seems to work in initial testing. Maybe it should also be reported in the log what values are used. I am closing this issue for now.
