### ISSUE TITLE
Single Change Point Calculator

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#11]
Could you please update the single change point calculator tool and add the following:
- radio button: add segments table
- radio button: add position
Make it in such a way that it can be used to fit either lines or levels.

Thank you :)

**Comment by karlduderstadt** [comment]
Hi @NadiaHuisjes,

Thanks for requesting these features. I agree this would all be awesome and in fact it has been added a while ago, but didn't get back here until now.

KCP is all in mars-core. These features have now been added and are ready for further testing. Closing this issue. If there are further features needed or issues related to this tool please report them in mars-core.
