### ISSUE TITLE
Rescaling of the Image and Plane fields in the metadata tab

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#13]
At the moment when no specific plane of the metadata record is selected, no scroll bars are displayed in the 'Image' and 'Plane' windows. It would enhance the aesthetics of the screen if this could be incorporated. Also the scaling of the column headers can look a bit clumsy when no specific plane is loaded.

**Comment by karlduderstadt** [comment]
This appears to be the default settings for these types of panes. I guess this is how they think they should look. I am not entirely sure how to change this, unfortunately. So I am going to close this issue for now and I/we can reopen it if it becomes a larger problem. Hope that's alright.
