### ISSUE TITLE
Peak Finder unstable

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#19]
I tested the peak finder on TestVideo.tif and found that it often does the right thing, except for the following two cases:

1. When you already ran the peak finder to generate a table once and leave it open, if you select the command again, change the 'T', then run the command without doing a preview first, it does not generate any output at all. Upon rerunning the command the selection of preview before execution it generates the correct output (and an additional table).
2. When you already ran the peak finder and generated a table once, then close the table, select the command again, change 'T' without doing a preview first, then run the command, a table is generated for the wrong 'T'-value (in fact for the last T value where you did a preview for). See screenshots for this error. Settings applied (T=0), table obtained (T=6).

Both errors are resolved by ticking the preview box before running the command.

<img width="634" alt="Screenshot 2020-09-10 at 17 21 14" src="https://user-images.githubusercontent.com/61824826/92753587-5082b080-f38a-11ea-955d-54dfaade0d1e.png">
<img width="712" alt="Screenshot 2020-09-10 at 17 21 23" src="https://user-images.githubusercontent.com/61824826/92753592-51b3dd80-f38a-11ea-9fe1-52e2907128ac.png">

**Comment by karlduderstadt** [comment]
Hi @NadiaHuisjes,

Thanks for reporting this issue. I think I understand the problem from your very good description. Basically, when running peak finder to find peaks in individual frames, the expectation is that peaks should be found for the time point T selected next to the preview button. At the moment, this setting is only considered when running preview, but we can certainly change it. 

I think it makes sense to have it run the peak finder on the frame specified in the T scrollbar. Should be simple to add the change.

Just FYI, if you have a table open and generate a new table that contains exactly the same values (from the same frame, same setting, for example), the table will not open. Basically, scijava checks and stops the display if the data contained inside are identical. So I don't have a way around that.

**Comment by karlduderstadt** [comment]
Commit duderstadt-lab/mars-core@14b2541 fixes this issue by always using the frame selected in the preview slider.

If you run the peak finder with exactly the same settings and don't close the table created inbetween, no table will open the second time. As explained above this is a feature of Fiji that it will not display a table with the same values. We could consider a work around but I guess maybe this behaviour is good and expected?
