### ISSUE TITLE
Refresh issue in the histogram scriptable widget

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#34]
Hi Karl! I observed a problem with refreshing in the histogram scriptable widget.
When I change the 'ymin,ymax' settings and press refresh only the axes labels are refreshed, not the actual graph itself. When I then press refresh a second time also the graph refreshes. Can you please take a look at this? I think it might have something to do with the order in which you read the input and do the refreshing perhaps?
I did not test this for the other scriptable widget types yet.

Thanks!

**Comment by karlduderstadt** [comment]
I was also the reproduce this problem. I think the behaviour is expected for all chart widgets and derives from the update mechanism. The commit above replaces a simple layout call on the charts with a layoutChildren call placed in a runLater block. This places the refresh at the end of the line and ensures it respects the new axis limits. A quick tests suggest this fixes the issue, so I will close it for now. Thanks for reporting and please reopen if it comes up again.

A very similar issue came up in the normal chart tab in molecule records and for MarsTables. Upon executing resetXYZoom() the axis and plot do not match. In that case somehow the above trick has not fixed the issue. The current workaround is to call resetXYZoom() method twice in a row in AbstractPlotPane. In the future a better solution should be found. The workaround will result in lower performance.
