### ISSUE TITLE
Removing Molecule Parameters

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#4]
I have an issue with removing molecule parameters using the 'tools>Delete Molecule Parameters' function.
- When putting a specified parameter in and pressing OK, the parameter is not removed.
- When removing all parameters, all parameters are removed.

**Comment by karlduderstadt** [comment]
Hi @NadiaHuisjes,

I can reproduce the issue. When I attempt to delete one parameter using the top part it doesn't nothing. But all parameters are removed. I will investigate why this is happening.

**Comment by karlduderstadt** [comment]
This fixed the issue for me. Can you confirm?

**Comment by NadiaHuisjes** [comment]
Thank you! It works indeed.
