### ISSUE TITLE
Can not close BigDataViewer window after closing molecule archive

### ISSUE THREAD

**Issue by thoretz** [duderstadt-lab/mars-fx#57]
I was about to close my molecule archive and analyze a new experiment. So I closed the archive which I had currently open. Then I tried to close the BigDataViewer window which opened via the archive. But instead of closing it, I got the following error message. So I closed Fiji and restarted it. 
![Screenshot 2022-04-05 at 13 10 47](https://user-images.githubusercontent.com/61778269/161761192-7bf117ee-cbe1-4099-b7dd-fc33e5e079d2.png)
It is just a minor thing but it would be nice if the BDV closes together with the archive. 

Thanks a lot in advance!

**Comment by karlduderstadt** [comment]
This appears to be fixed, lets reopen if it reappears. I did however notice a memory leak when using BDV windows that prevents release of the Molecule Archive memory... That is now a new issue #78
