### ISSUE TITLE
Adjustable y-axis in histogram widget

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#6]
Hi Karl,

Can you please add the option to let the user define the desired ymin and ymax for the histogram plot? The default may still be that it auto adjusts to the largest value in the dataset.
Thank you!

**Comment by NadiaHuisjes** [comment]
And could you also add this to the category plot widget?

**Comment by karlduderstadt** [comment]
That is a great idea. Now you can add ymin and ymax outputs and they will modify the y-axis. If only ymax is provided it will assume ymin=0. If only ymin is provided it will have no effect. It seems you can either auto scale the whole axis or not, so I don't see a way to work with ymin alone as an input.

Thanks for this suggestion. Please test and let me know if this is working for you.

**Comment by NadiaHuisjes** [comment]
It works like you said it would! Great!
