### ISSUE TITLE
Grey bar appearing in scriptable widgets

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-fx#8]
Sometimes, when working with the scriptable widgets, a small grey bar above the chart title appears. It does not seem to have a function for the user. Can this be removed?

<img width="493" alt="Screenshot 2020-05-12 at 14 57 00" src="https://user-images.githubusercontent.com/61824826/81695259-b0139280-9462-11ea-9ef9-f7d6534f3f39.png">

**Comment by karlduderstadt** [comment]
I set the trigger displace to zero for all dashboard widgets. This appears to prevent the grey bar from appearing. So chartfx uses controlfx hidden sides pane and it is for this pane the trigger distance is being set. Usually this would trigger a toolbar to appear but this in case we don't want a toolbar. Please test and report back about whether the grey bar is now gone.

**Comment by NadiaHuisjes** [comment]
The grey bar has not appeared ever since the update. Seems to work fine now!
