### ISSUE TITLE
!notThisTag

### ISSUE THREAD

**Issue by filipovicf** [duderstadt-lab/mars-fx#84]
I have a small suggestion. Would it be possible to implement an exclusion tag when sorting molecules? Namely, by adding an exclamation mark before the tag, is it possible to exclude the molecules containing this tag (!notThisTag)? This would make sifting through the data much faster :D

**Comment by karlduderstadt** [comment]
Yes I totally agreed we should have this! I just added this but it might take a little while before it makes it to the update site. Other changes need a bit more testing.

I have not yet added this to tag search of metadata records. I would like that tag search to have all the same features eventually.

**Comment by filipovicf** [comment]
Perfect! I guess that means that it doesn't yet work for the virtual store, but it works for the archive?On Jun 23, 2023 16:44, karlduderstadt ***@***.***> wrote:
Yes I totally agreed we should have this! I just added this but it might take a little while before it makes it to the update site. Other changes need a bit more testing.
I have not yet added this to tag search of metadata records. I would like that tag search to have all the same features eventually.

**Comment by karlduderstadt** [comment]
No it should also work for virtual archives. The UI code is the same for both. All the differences live in mars-core. I will work on getting it released to the update site so you can test it. The other changes are the inclusion of cloud support for N5 datasets. This will include a new jar mars-minio. I will add everything to the update site over the weekend.
