### ISSUE TITLE
Tag shortcuts are not activated by default

### ISSUE THREAD

**Issue by mjosch** [duderstadt-lab/mars-fx#9]
Dear Martians,

I encountered a minor issue regarding tag shortcuts in archives. Once a new archive is loaded, preset tag shortcuts only become active after selecting (clicking on) the settings tab at least once

<img width="55" alt="Bildschirmfoto 2020-05-13 um 09 27 11" src="https://user-images.githubusercontent.com/39280948/81784320-f9182500-94fc-11ea-8443-316552e49883.png">

**Comment by karlduderstadt** [comment]
Hi @mjosch,

Thanks for reporting. I could reproduce this problem. Now the hotkey are initialised without a need to visit the settings tab first. Please confirm this fixes the issue on your side.

**Comment by mjosch** [comment]
Hi @karlduderstadt,

The issue seems fixed with the latest update, thanks!
